MakeAChoice DEFINITIONS AUTOMATIC TAGS ::= BEGIN

Collection ::= SEQUENCE {
    the_choice CHOICE {
        hello OCTET STRING,
        goodbye OCTET STRING,
        integer INTEGER,
        boolean BOOLEAN
    }
}

END
