MakeAChoice DEFINITIONS IMPLICIT TAGS ::= BEGIN

Collection ::= SEQUENCE {
    the-choice CHOICE {
        hello [0] OCTET STRING,
        goodbye [1] OCTET STRING,
        integer [2] INTEGER,
        boolean [3] BOOLEAN,
        sequence [4] SEQUENCE { i INTEGER }
    }
}

END
