ModuleA DEFINITIONS IMPLICIT TAGS ::= BEGIN
IMPORTS
    StringInModuleB, string-value FROM ModuleB
    IntegerInModuleC, integer-value FROM ModuleC;

Collection ::= SEQUENCE {
    string StringInModuleB,
    integer IntegerInModuleC
}

END

ModuleB DEFINITIONS IMPLICIT TAGS ::= BEGIN
EXPORTS StringInModuleB;

StringInModuleB ::= OCTET STRING

string-value StringInModuleB ::= "pear"

END

ModuleC DEFINITIONS IMPLICIT TAGS ::= BEGIN
EXPORTS IntegerInModuleC;

IntegerInModuleC ::= INTEGER

integer-value IntegerInModuleC ::= 5

END
