Sequence

DEFINITIONS EXPLICIT TAGS ::=

BEGIN

NamedType     ::= OCTET STRING
SequenceOne   ::= SEQUENCE OF OCTET STRING
SequenceTwo   ::= SEQUENCE OF NamedType
SequenceThree ::= SEQUENCE OF named-string OCTET STRING

END
