Simple DEFINITIONS AUTOMATIC TAGS ::= BEGIN

Collection ::= SEQUENCE {
    hello OCTET STRING,
    goodbye OCTET STRING,
    integer INTEGER,
    boolean BOOLEAN,
    child Child,
    optional_child Child OPTIONAL,
    the_choice CHOICE {
        hello OCTET STRING,
        goodbye OCTET STRING,
        integer INTEGER,
        boolean BOOLEAN
    }
}

Child ::= SEQUENCE {
    meaning_of_life INTEGER OPTIONAL,
    list SEQUENCE OF OCTET STRING
}

END
