Tags DEFINITIONS IMPLICIT TAGS ::= BEGIN

Collection ::= SEQUENCE {
    string1 [0] OCTET STRING,
    string2 [1] OCTET STRING,
    integer [2] EXPLICIT INTEGER,
    bool1 [3] IMPLICIT BOOLEAN,
    bool2 [PRIVATE 4] EXPLICIT BOOLEAN,
    bool3 [APPLICATION 5] BOOLEAN
}

END
